#!/bin/bash

## WRITE HEADER BRAD

module load mricron

topdir="/N/dc2/projects/lifebid/Concussion/concussion/group3/"
subj="3_044"

## Indices refer to the 
## T1 (ANATOMY, 1) 
## DWI (PA diffusion, 10) 
## DWI (AP diffusion, 11) 
files="2 10 11"

for subj in $subjects
  do
    for FILES in $files
      do
        cd $topdir/$subjects/$FILES
        
        ## This operation will create BVECS/BVALS and NIFTI
        dcm2nii ./1_${FILES}_dicoms
      done
  done
