#!/bin/bash -x

## Script for preprocessing both phase encoding directions and combining to singular dti file.  Developed by Hu Cheng, Ph.D from Indiana University, compiled into script by Brad Caron, IU graduate student, and used for project on microstructure of 
## concussion-prone athletics.

## Load modules
module load fsl/5.0.9

## Set up variables
rootpath="/N/dc2/projects/lifebid/Concussion/concussion_test";
subj="1_5";
diffdir1="$rootpath/$subj/diffusion_directory/diffusion";
diffphase="PA AP";

## Eddy-current correction, reorganization of output from eddy_current correction, combination to make a no
## -diffusion mean file, and perform brain extraction on both phase encoding directions

for phase in $diffphase
	do
		cd $diffdir1/$phase;
		eddy_correct $phase r$phase 0;
		. $rootpath/$subj/diffusion_directory/bin/reorgDTI r$phase;
		fslmaths nodif -Tmean $phase_nodif_mean;
		bet $phase_nodif_mean nodif_brain -f 0.4 -g 0 -m;
done

## Merge directions, apply top-up, fit tensors

cd $diffdir1
fslmerge -t b0_images ./PA/PA_nodif_mean ./AP/AP_nodif_mean
topup --imain=b0_images.nii.gz --datain=acq_params.txt --config=b02b0.cnf --out=my_topup_results --fout=my_field --iout=my_unwarped_images
applytopup --imain=./PA/rPA.nii.gz,./AP/rAP.nii.gz --datain=acq_params.txt --inindex=1,2 --topup=my_topup_results --out=data
bet data nodif_brain -f 0.4 -g 0 -m
dtifit --data=data --out=dti --mask=nodif_brain_mask --bvecs=bvecs --bvals=bvals

