#!/bin/bash -x

## Script to call to matlab to realign t1 to ac-pc using mrAnatAverageAcpcNifti.  Created by Brad Caron (Indiana University graduate student) for study on white matter microstructure in concussion-prone athletics 2016.

## load modules
module load fsl/5.0.9

## Set up variables
datadir1="/N/dc2/projects/lifebid/Concussion/concussion_test";  # Data directory; replace with your data directory set-up.
subj="1_5";  # subjects for study; include all subjects once data directory is set-up properly
diffdir1="$datadir1/$subj/diffusion_directory/Anatomy"; # path to Anatomy directory

for subjects in $subj
	do
		cd $diffdir1
		cp /N/dc2/projects/lifebid/code/bacaron/pestillilab_projects/Concussion/ACPC_script.m ./ACPC_script.m		 
		matlab -r "ACPC_script"
		bet t1_acpc.nii.gz t1_acpc_brain.nii.gz -m -f 0.25
done
