#!/bin/bash
dir1=`pwd`;
diffdir=${dir1}'/diffusion'
cd $diffdir;
cd PA;
eddy_correct PA rPA 0
reorgDTI rPA;
fslmaths nodif -Tmean PA_nodif_mean
bet PA_nodif_mean nodif_brain -f 0.4 -g 0 -m
cd ..
cd AP;
eddy_correct AP rAP 0
reorgDTI rAP;
fslmaths nodif -Tmean AP_nodif_mean
bet AP_nodif_mean nodif_brain -f 0.4 -g 0 -m
cd ..
fslmerge -t b0_images ./PA/PA_nodif_mean ./AP/AP_nodif_mean
topup --imain=b0_images.nii.gz --datain=acq_params.txt --config=b02b0.cnf --out=my_topup_results --fout=my_field --iout=my_unwarped_images
applytopup --imain=./PA/rPA.nii.gz,./AP/rAP.nii.gz --datain=acq_params.txt --inindex=1,2 --topup=my_topup_results --out=data
bet data nodif_brain -f 0.4 -g 0 -m
dtifit --data=data --out=dti --mask=nodif_brain_mask --bvecs=bvecs --bvals=bvals
bedpostx $diffdir --nf=2 --fudge=1  --bi=1000 --model=2
