#!/bin/bash

module load mricron

topdir="/N/dc2/projects/lifebid/Concussion/concussion/group3/"
subj="3_044"
files="2 10 11"

for subj in $subjects
  do
    for FILES in $files
      do
        cd $topdir/$subjects/$FILES
        dcm2nii ./1_${FILES}_dicoms
      done
  done
