#!/bin/bash -x

## Set up variables
rootpath="/N/dc2/projects/lifebid/Concussion/concussion_test";
subj="1_5";
diffdir1="$rootpath/$subj";
stem="data"

for subjects in $subj
	do
		cd $diffdir1/diffusion_data
		mkdir 1000
		mkdir 2000
		mkdir 1000/raw
		mkdir 2000/raw
		cp $diffdir1/diffusion_directory/Anatomy/t1_acpc_brain.nii.gz ./1000/t1_acpc_bet.nii.gz
		cp $diffdir1/diffusion_directory/Anatomy/t1_acpc_brain.nii.gz ./2000/t1_acpc_bet.nii.gz
		cp ./data_b1000.bvals ./1000/raw/bvals
		cp ./data_b1000.bvecs ./1000/data_b1000.bvecs
		cp ./data_b1000.nii.gz ./1000/raw/data_b1000.nii.gz
		cp ./data_b2000.bvals ./2000/raw/bvals
		cp ./data_b2000.bvecs ./2000/bvecs
		cp ./data_b2000.nii.gz ./2000/raw/data_b2000.nii.gz
		cp /N/dc2/projects/lifebid/Concussion/concussion3/1_5/diffusion_data/1000/bvecs_real2a ./1000/raw/bvecs_real2a
		cp /N/dc2/projects/lifebid/Concussion/concussion3/1_5/diffusion_data/1000/bvecs_real2a ./2000/raw/bvecs_real2a
		cp /N/dc2/projects/lifebid/code/bacaron/pestillilab_projects/Concussion/dti_init_batch.m ./dti_init_batch.m		
		matlab -r "dti_init_batch"
done

