#!/bin/bash

#PBS -k o
#PBS -l nodes=1:ppn=16,walltime=20:00:00
#PBS -N FS_HQ

module load fsl/5.0.9
module load freesurfer

export SUBJECTS_DIR=/N/dc2/projects/lifebid/Concussion/test/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

subj="1_5";
projdir1="/N/dc2/projects/lifebid/Concussion/concussion_test";

for subjects in $subj
	do
		recon-all -s concuss_hq -i $projdir1/$subjects/diffusion_directory/Anatomy/t1_acpc.nii.gz - all
done



